/* eslint-disable */
// Generated by @convex-dev/cli@0.0.62
// based on the contents of this directory.
// To regenerate, run `convex codegen`.
import type { addChoice as addingChoices__addChoice } from "./addingChoices";
import type { doneAdding as addingChoices__doneAdding } from "./addingChoices";
import type { startVoting as addingChoices__startVoting } from "./addingChoices";
import type getInstance from "./getInstance";
import type loggedInUser from "./loggedInUser";
import type startInstance from "./startInstance";
import type { currentRanking as voting__currentRanking } from "./voting";
import type { doneVoting as votingMutation__doneVoting } from "./votingMutation";
import type { votingMutation as votingMutation__votingMutation } from "./votingMutation";

type ConvexAPI = {
  queries: {
    getInstance: typeof getInstance;
    loggedInUser: typeof loggedInUser;
    "voting:currentRanking": typeof voting__currentRanking;
  };
  mutations: {
    "addingChoices:addChoice": typeof addingChoices__addChoice;
    "addingChoices:doneAdding": typeof addingChoices__doneAdding;
    "addingChoices:startVoting": typeof addingChoices__startVoting;
    startInstance: typeof startInstance;
    "votingMutation:doneVoting": typeof votingMutation__doneVoting;
    "votingMutation:votingMutation": typeof votingMutation__votingMutation;
  };
};

import {
  makeUseQuery,
  makeUseMutation,
  makeUseConvex,
} from "@convex-dev/react";

export const useQuery = makeUseQuery<ConvexAPI>();
export const useMutation = makeUseMutation<ConvexAPI>();
export const useConvex = makeUseConvex<ConvexAPI>();
